---
title: "The correlation report template"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{The correlation report template}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  eval = FALSE
)
```

The correlation report template can be found [here](https://github.com/NOAA-EDAB/NEesp/tree/dev/inst/correlation_bookdown_template).

## The index file

The [index file](https://github.com/NOAA-EDAB/NEesp/blob/main/inst/correlation_bookdown_template/index.Rmd) contains important set-up information for the report. Report specifications, including parameters, are defined in the YAML frontmatter. Data is read in and trimmed to only the stock of interest. Some null variables are set for later use in the report, and there is a fail message that is output if no data exists for the parameters selected. 

## The indicator chapters

Each chapter regresses an ecosystem indicator from the [`ecodata` package](https://github.com/NOAA-EDAB/ecodata) against a stock parameter (abundance, recruitment, F, and catch). Because all `ecodata` data sets are in a standard format, the chapter analyses are conducted with a child document. Each indicator is assigned to a generic variable name and then passed to the child document with the [`render_indicator` function](https://noaa-edab.github.io/NEesp/reference/render_indicator.html) (e.g., [the physical indicators](https://github.com/NOAA-EDAB/NEesp/blob/main/inst/correlation_bookdown_template/02-physical-indicators.Rmd)). Some indicators have a small amount of pre-processing if necessary, for example selecting only one season of the indicator for the analysis. 

The [child document](https://github.com/NOAA-EDAB/NEesp/blob/main/inst/correlation_bookdown_template/_general-child-doc.Rmd) first merges the indicator data with the stock data and saves the data to the report output. Information about the stock-indicator correlations is recorded for the summary section. 

Data is [plotted](https://noaa-edab.github.io/NEesp/reference/plot_correlation.html). If any correlations were statistically significant, the correlation information is [displayed](https://noaa-edab.github.io/NEesp/reference/correlation_data.html). 

Finally, more information about the statistically significant correlations is recorded for the summary section.

## The summary chapter

The [summary chapter](https://github.com/NOAA-EDAB/NEesp/blob/main/inst/correlation_bookdown_template/08-summary.Rmd) displays information about all of the statistically significant indicator-stock correlations from the report. An exploratory Generalized Linear Model is created using forward step wise selection of indicators statistically significant at the Bonferroni-corrected level.

## The appendix

The final chapter in the `bookdown` template is [an appendix](https://github.com/NOAA-EDAB/NEesp/blob/main/inst/correlation_bookdown_template/appendix.Rmd), which displays R session and package information.