---
title: "The indicator report template"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{The indicator report template}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  eval = FALSE
)
```

## The index file

The [index file](https://github.com/NOAA-EDAB/NEesp/blob/main/inst/indicator_bookdown_template/index.Rmd) contains important set-up information for the report. Report specifications, including parameters, are defined in the YAML frontmatter. Data is read in, trimmed to only the stock of interest, and saved as a report output. 

## The chapters

Each chapter displays indicator information about the stock (e.g., [the abundance section](https://github.com/NOAA-EDAB/NEesp/blob/main/inst/indicator_bookdown_template/abundance.Rmd)). Data visualizations are created primarily with functions, to minimize the amount of code in the report template. All data manipulation and visualization contains conditional statements to handle missing data (either explicitly included in the template code, or in the back-end visualization functions).

## The appendix

The final chapter in the `bookdown` template is [an appendix](https://github.com/NOAA-EDAB/NEesp/blob/main/inst/indicator_bookdown_template/appendix.Rmd), which displays R session and package information.