---
title: "Creating the risk assessment"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Creating the risk assessment}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  eval = FALSE
)
```

## What is risk assessment?

Risk assessment is a structured method to identify issues of concern, which can be used to systematically identify and prioritize action items. Therefore, risk assessment is a useful first step to approach decision making in fisheries management, and it [has been used](https://www.frontiersin.org/articles/10.3389/fmars.2018.00442/full) by the Mid-Atlantic Fisheries Management Council to prioritize research plans for an Ecosystem Approach to Fisheries Management. In approaching the preliminary Ecosystem and Socioeconomic Profiles (ESPs) for Northeast stocks, we conducted a risk assessment to determine which stocks would benefit most from an ESP. This risk assessment involved aggregating existing data about stock ecology and socioeconomics and determining whether indicators were trending favorably or unfavorably for each stock.

## The NRCC risk assessment

The [Northeast Region Coordinating Council (NRCC)](https://www.nefmc.org/committees/northeast-regional-coordinating-council-nrcc) is the organizational body responsible for setting the stock assessment schedule in the Northeast. In 2016-2017, the NRCC developed a [risk assessment process](https://s3.amazonaws.com/nefmc.org/Stock-assessment-process-June2020.pdf) to inform the setting of [research and management track stock assessment schedules](https://www.nefmc.org/library/2020-2024-stock-assessment-schedule).

## The ESP risk assessment

The goals of the ESP (providing ecosystem and socioeconomic advice for stock management) differ from the goals of the NRCC (setting the stock assessment schedule). Therefore, we conducted our [own risk assessment](https://noaa-edab.github.io/ESP_docs/risk_ranking/plot_all_risk) to determine which stocks would benefit most from an ESP. As part of our risk assessment, we identified which stocks were of most socioeconomic importance and which stocks exhibited concerning ecosystem and socioeconomic trends. Stocks were ranked from least concern to most concern for each indicator, and then ranks were normalized. If a stock was missing a measurement, it was assigned a normalized rank of 0.5. The total risk for each stock was calculated as the sum of all normalized rankings. 

This risk assessment is intended to be a guideline for ESP prioritization, not a rigid directive for ESP scheduling.

### Comprehensive risk

Using the [`NEesp::get_risk` function](https://noaa-edab.github.io/NEesp/reference/index.html#section-risk-data-suite-of-functions), each stock was assigned a single risk value for each indicator based on its normalized rank relative to other stocks. Depending on the indicator, indicator time series were reduced to a single value either by (1) only considering the most recent value, (2) taking the mean of the past 5 years, (3) taking the maximum of all time, or (4) comparing the mean of the past 10 years to the historical mean. After normalized species risks were calculated for each indicator, risk data was combined into a single data set, missing values were assigned a value of 0.5, and total risk value and ranks were calculated for each stock. The full data manipulation script can be seen [here](https://github.com/NOAA-EDAB/NEesp/blob/main/data-raw/scripts/create_risk_rankings/calculate_comprehensive_risk.R). 

### Comprehensive risk by guild

### Risk within species, value over time

Within each species, indicators were ranked over time to assign a risk value. Depending on the indicator, high value was assigned high risk, or low value was assigned high risk. The purpose of this calculation was to visualize the temporal trend of a stock's indicator. The full data manipulation script can be seen [here](https://github.com/NOAA-EDAB/NEesp/blob/main/data-raw/scripts/create_risk_rankings/calculate_risk_within_species.R).

### Risk across species, value over time

For each year, stocks were ranked by their indicator values. Depending on the indicator, high value was assigned high risk, or low value was assigned high risk. The purpose of this calculation was to visualize the temporal trend of a stock's status relative to other stocks. The full data manipulation script can be seen [here](https://github.com/NOAA-EDAB/NEesp/blob/main/data-raw/scripts/create_risk_rankings/calculate_value_rankings_over_time.R).

### Risk across species, change compared to historical over time

For each year, stocks were ranked by their indicator values, which were normalized to the historical value. Depending on the indicator, high value was assigned high risk, or low value was assigned high risk. The purpose of this calculation was to visualize the temporal trend of a stock's status relative to other stocks, accounting for a baseline measurement of the indicator. The full data manipulation script can be seen [here](https://github.com/NOAA-EDAB/NEesp/blob/main/data-raw/scripts/create_risk_rankings/calculate_historical_rankings_over_time.R).
