---
title: "Why ESP?"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Why ESP?}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Ecosystem Based Management

The development and implementation of [Ecosystem Based Management](https://ecosystems.noaa.gov/Home.aspx) (EBM) is one of NOAA's operating priorities.

## Integrated Ecosystem Assessment

[Integrated Ecosystem Assessment](https://www.integratedecosystemassessment.noaa.gov/) (IEA) seeks to improve understanding and management of fisheries through incorporating natural, social, and economic data into fisheries analyses and management plans. Ecosystem and Socioeconomic Profiles (ESPs) are a structured framework to facilitate the inclusion of ecosystem and socioeconomic data in the stock advice process. Generally, ESPs consist of three components: 
1. Stock metrics: information about the stock
2. Ecosystem and socioeconomic indicators: relevant information about the ecosystem and human dimensions
3. Analysis: Correlation and other modeling of relationships between stock metrics and ecosystem and socioeconomic indicators; summaries of current conditions and determination as to qualitative "favorability" for the stock.
Within this general framework, ESPs have a flexible structure that allows for both quantitative and qualitative data and a variety of tailored analyses depending on the stock details. This flexibility makes ESPs a practicable method for implementing Ecosystem Based Fisheries Management in the Northeast. 

## Operationalizing the SOE reports

The State of the Ecosystem (SOE) reports have been positively received by both the Northeast and Mid Atlantic Fisheries Management Councils. However, the SOEs are general reports and do not easily translate into management advice for most stocks. 

### Ecosystem data on the stock scale

ESPs re-calculate SOE data on the stock scale, which allows for the exploration of stock-relevant ecosystem and socioeconomic trends. 

## Open data science

We are approaching ESP development through the lens of open data science. This means that our process is oriented around open access to data and transparent methods.

### Making data accessible

The `NEespShiny` app queries the `NEesp` and `ecodata` package for data relevant to a stock of interest. Preliminary, skeleton reports are created with visualizations of the data. Additionally, all data are provided to the user for download. 

