name: 'Create reports'
description: 'Render and deploy ESP reports'
inputs:
  species:  #  species indices
    description: 'Which all_species to include (numeric)'
    required: true
    default: '1'
    
defaults:
  run:
    shell: bash
  
runs:
   using: "composite"
   steps:
   
      - uses: actions/checkout@v2
        
      - uses: r-lib/actions/setup-r@master

      - run: brew install pandoc

      - uses: actions/cache@v1
        id: cache
        with:
          path: ${{ env.R_LIBS_USER }}
          key: big-cache-3dfeec915c65af830b4ce8d69a745ee510b348f69532ef96ae49f0082eadd7c3

      - run: |        
          sudo R CMD javareconf
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libgdal-dev
          sudo apt-get install libgit2-dev 
          sudo apt-get install libudunits2-dev
          
      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Rscript -e 'install.packages("devtools")
          devtools::install_deps(dependencies = TRUE)'

      - run: |
          nums <- ${{ inputs.species }}
          source(here::here("bookdown/render", "render_bookdown_ghaction.R"))
        shell: Rscript {0}

      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/action_reports # The folder the action should deploy.
          TARGET_FOLDER: docs
          CLEAN: true # Automatically remove deleted files from the deploy branch
