## Trophic indicators in the stock region

### Chlorophyll in stock region
```{r, chl-stock}
test <- ecodata::ESP_seasonal_chl %>%
  dplyr::mutate(Pattern_check = ESP %>%
    stringr::str_replace_all("_", " ") %>%
    stringr::str_to_sentence()) %>%
  dplyr::filter(stringr::str_detect(Pattern_check, params$stock)) %>%
  dplyr::distinct()

if (nrow(test) > 0) {
  if (length(unique(test$Pattern_check)) > 1) {
    # add stock region into var for faceting
    test <- test %>%
      dplyr::mutate(Var = paste(Var, Pattern_check, sep = " ") %>%
        stringr::str_replace_all("_", "") %>%
        stringr::str_wrap(width = 8))
    NEesp::render_indicator(test, lab = names[1])
  } else {
    test <- test %>%
      dplyr::mutate(Var = paste0(Var, "_stock"))

    NEesp::render_indicator(test, lab = names[1])
  }
} else {
  "Indicator data has not been parsed over this stock's region"
}
```

### Primary production in stock region
```{r, pp-stock}
test <- ecodata::ESP_seasonal_pp %>%
  dplyr::mutate(Pattern_check = ESP %>%
    stringr::str_replace_all("_", " ") %>%
    stringr::str_to_sentence()) %>%
  dplyr::filter(stringr::str_detect(Pattern_check, params$stock)) %>%
  dplyr::distinct()

if (nrow(test) > 0) {
  if (length(unique(test$Pattern_check)) > 1) {
    # add stock region into var for faceting
    test <- test %>%
      dplyr::mutate(Var = paste(Var, Pattern_check, sep = " ") %>%
        stringr::str_replace_all("_", "") %>%
        stringr::str_wrap(width = 8))
    NEesp::render_indicator(test, lab = names[1])
  } else {
    test <- test %>%
      dplyr::mutate(Var = paste0(Var, "_stock"))

    NEesp::render_indicator(test, lab = names[1])
  }
} else {
  "Indicator data has not been parsed over this stock's region"
}
```

### Zooplankton in the stock region

#### Annual zooplankton abundance in the stock region
```{r, zoop-stock-annual}
if (params$stock == "Black sea bass") {
  # load data
  test_big <- NEesp::zoop_stock %>%
    dplyr::filter(
      Species == params$stock,
      Season == "Annual"
    ) %>%
    dplyr::select(-Species, -Season)
  colnames(test_big) <- paste(colnames(test_big), "_annual", sep = "")
  
  zoop_length <- length(colnames(test_big)) - 1 # don't count time column
  zoop_names <- colnames(test_big)[1:zoop_length]

  # update names for saving figs
  names <- c(zoop_names, names[-1])

  # loop child doc
  for (i in 1:zoop_length) {
    test <- tibble::tibble(
      Time = test_big$Time,
      Var = colnames(test_big)[i],
      Val = test_big[, i]
    )
    # make section title
    title <- names[1] %>%
      stringr::str_replace_all("_", " ") %>%
      stringr::str_to_title()
    cat(paste("####", title, "{-}"), "\n\n")

    # render section
    NEesp::render_indicator(test, lab = names[1])
  }
} else {
  "No data for this species yet"
}
```

#### Spring zooplankton abundance in the stock region
```{r, zoop-stock-spring}
if (params$stock == "Black sea bass") {
  # load data
  test_big <- NEesp::zoop_stock %>%
    dplyr::filter(
      Species == params$stock,
      Season == "Spring"
    ) %>%
    dplyr::select(-Species, -Season)
  colnames(test_big) <- paste(colnames(test_big), "_spring", sep = "")
  
  zoop_length <- length(colnames(test_big)) -1
  zoop_names <- colnames(test_big)[1:zoop_length]

  # update names for saving figs
  names <- c(zoop_names, names[-1])

  # loop child doc
  for (i in 1:zoop_length) {
    test <- tibble::tibble(
      Time = test_big$Time,
      Var = colnames(test_big)[i],
      Val = test_big[, i]
    )

    # make section title
    title <- names[1] %>%
      stringr::str_replace_all("_", " ") %>%
      stringr::str_to_title()
    cat(paste("####", title, "{-}"), "\n\n")

    # render section
    NEesp::render_indicator(test, lab = names[1])
  }
} else {
  "No data for this species yet"
}
```

#### Fall zooplankton abundance in the stock region
```{r, zoop-stock-fall}
if (params$stock == "Black sea bass") {
  # load data
  test_big <- NEesp::zoop_stock %>%
    dplyr::filter(
      Species == params$stock,
      Season == "Fall"
    ) %>%
    dplyr::select(-Species, -Season)
  colnames(test_big) <- paste(colnames(test_big), "_fall", sep = "")

  zoop_length <- length(colnames(test_big)) -1
  zoop_names <- colnames(test_big)[1:zoop_length]

  # update names for saving figs
  names <- c(zoop_names, names[-1])

  # loop child doc
  for (i in 1:zoop_length) {
    test <- tibble::tibble(
      Time = test_big$Time,
      Var = colnames(test_big)[i],
      Val = test_big[, i]
    )
    # make section title
    title <- names[1] %>%
      stringr::str_replace_all("_", " ") %>%
      stringr::str_to_title()
    cat(paste("####", title, "{-}"), "\n\n")

    # render section
    NEesp::render_indicator(test, lab = names[1])
  }
} else {
  "No data for this species yet"
}
```