# Summary of statistically significant indicators

```{r, output_summary_html, eval = (params$out == "html")}
summary_table <- function(x) {
  DT::datatable(x,
    rownames = FALSE,
    filter = list(
      position = "top",
      clear = FALSE
    ),
    options = list(
      search = list(regex = TRUE),
      paging = FALSE
    )
  )
}
```

```{r, output_summary_word, eval = (params$out == "word")}
summary_table <- function(x) {
  knitr::kable(x)
}
```

```{r}
colnames(output) <- c(
  "Response_variable", "Indicator",
  "Number of data points", "Slope",
  "P-value", "R2_adj"
)
```

## Abundance
```{r}
output %>%
  tibble::as_tibble() %>%
  dplyr::filter(
    Response_variable == "Abundance",
    R2_adj < 1
  ) %>%
  dplyr::select(-Response_variable) %>%
  summary_table()
```

## Recruitment
```{r}
output %>%
  tibble::as_tibble() %>%
  dplyr::filter(
    Response_variable == "Recruitment",
    R2_adj != 1
  ) %>%
  dplyr::select(-Response_variable) %>%
  summary_table()
```

## Catch
```{r}
output %>%
  tibble::as_tibble() %>%
  dplyr::filter(
    Response_variable == "Catch",
    R2_adj != 1
  ) %>%
  dplyr::select(-Response_variable) %>%
  summary_table()
```

## Fmort
```{r}
output %>%
  tibble::as_tibble() %>%
  dplyr::filter(
    Response_variable == "Fmort",
    R2_adj != 1
  ) %>%
  dplyr::select(-Response_variable) %>%
  summary_table()
```

