```{r}
# test if data even exists
if ("EPU" %in% colnames(test)) {
  eval_epu <- sum(test$EPU %in% params$epu) > 0 # only evaluate if the selected epu is in the indicator data set
} else {
  eval_epu <- TRUE
} # always evaluate if there is no epu for the indicator
```

````{r, eval = eval_epu}
# check data structure and average if necessary

# make sure test data has the right structure
if ("EPU" %in% colnames(test)) {
  test <- test %>%
    dplyr::filter(EPU %in% params$epu)
}

if ("Units" %in% colnames(test)) {
  test <- test %>%
    dplyr::mutate(Var = paste(Var, Units, sep = "\n"))
}

if ("Value" %in% colnames(test)) {
  test <- test %>%
    dplyr::rename(Val = Value)
}

# mean data by year
n_years <- length(unique(test$Time))
n_var <- length(unique(test$Var))
n_measurements <- length(test$Time)

if ((n_measurements > n_years * n_var) &
  (n_measurements > 0)) {
  test <- test %>%
    dplyr::mutate(Var = paste(Var, "(annual mean)", sep = "\n"))
  
  test <- test %>%
  dplyr::ungroup() %>%
  dplyr::group_by(Var, Time) %>%
  dplyr::summarise(new_val = mean(Val)) %>%
  dplyr::rename(Val = new_val) %>%
  dplyr::ungroup()
}

# make name for figure
knitr::opts_knit$set(unnamed.chunk.label = names[1])
```

```{r, eval = eval_epu}
# process data
data <- try(NEesp::data_prep(
  stock_data = stock,
  eco_data = test,
  lag_data = params$lag
))

if(class(data) == "try-error"){
  print("Data problems!")
  eval_epu <- FALSE
  print(head(stock))
  print(head(test))
}
```

```{r, eval = eval_epu, results = "asis"}
if(class(data) == "try-error") {
  print("There was a problem with this data!!")
  cat("\n\n")
  traceback()
  cat("\n\n")
  knitr::kable(head(test))
  cat("\n\n")
  knitr::kable(head(stock))
  eval_epu <- FALSE
}
```

```{r, eval = params$save & eval_epu}
  if (nrow(data) > 0) {
  name <- paste(params$stock, params$region, params$epu[1],
    params$lag, "lag",
    params$remove_recent, "rr", names[1],
    sep = "_"
  ) %>%
    stringr::str_replace_all("/", "-") %>%
    stringr::str_replace_all("Georges Bank", "GB") %>%
    stringr::str_replace_all("Gulf of Maine", "GOM") %>%
    stringr::str_replace_all("Northern", "N") %>%
    stringr::str_replace_all("Southern", "S") %>%
    stringr::str_replace_all("Northwestern", "NW") %>%
    stringr::str_replace_all(" - ", "-") %>%
    stringr::str_replace_all(" ", "_")
  
  objsize <- object.size(data)
  
      if (objsize < 10^4 ) {
        file_name <- paste("data/", name, ".csv", sep = "")
        write.csv(data, file_name)
      } else {
        file_name <- paste("data/", name, ".RDS", sep = "")
       saveRDS(data, file_name)
      }

  # prep for fig
  # remove na's,
  # count number of regressions for bonferroni correction
  data <- data %>%
    tibble::as_tibble() %>%
    tidyr::drop_na()
  var_names <- unique(data$Var)
  nvar <- length(var_names)
  bonf_n <- bonf_n + nvar
}
```

##### Figures {-}
```{r, eval = FALSE}
if(toString(quote({{label}})) == "pp-week" | toString(quote({{label}})) == "chl-week"){
  figs <- FALSE
  print("Too many figures! Showing statistical results only")
} else {
  figs <- eval_epu
}
```

```{r, {{label}}-fig, eval = eval_epu, fig.height = 10}
if (nvar > 6) { # break up into multiple graphs
  for (i in 1:round(nvar / 6)) {
    index <- ((i - 1) * 6 + 1):(i * 6)
    dat <- data %>%
      dplyr::filter(Var %in% var_names[index])

    NEesp::plot_correlation(
      data = dat,
      lag = params$lag
    )

    cat("\n\n")
  }
} else {
    fig <- NEesp::plot_correlation(
      data = data,
      lag = params$lag
    )
}
```

```{r, eval = (eval_epu == FALSE)}
print("No data for the EPU selected")
```

##### Regression statistics {-}
```{r, results = "asis", eval = eval_epu}
# correlation tables
NEesp::correlation_data(
  data = data,
  lag = params$lag
)

# correlation summary (to go at end of report)
output <- rbind(output, NEesp::correlation_summary(
  data = data,
  lag = params$lag
))
```

```{r, eval = eval_epu}
#### Regression data
this_recruit <- data %>%
  dplyr::filter(
    Metric == "Recruitment",
    sig == TRUE
  ) %>%
  dplyr::select(Species, Region, Time, Value, Metric, Var, Val, pval)

if (nrow(this_recruit) > 0) {
  recruit_data <- rbind(recruit_data, this_recruit)
}

this_abun <- data %>%
  dplyr::filter(
    Metric == "Abundance",
    sig == TRUE
  ) %>%
  dplyr::select(Species, Region, Time, Value, Metric, Var, Val, pval)

if (nrow(this_abun) > 0) {
  abun_data <- rbind(abun_data, this_abun)
}
```

```{r, eval = (eval_epu == FALSE)}
print("No data for the EPU selected")
```

```{r}
names <- names[-1]
```
