---
title: "`r params$species_ID`"
author: "Abigail Tyrell"
date: "`r format(Sys.time(), '%d %b %Y')`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    split_by: section
documentclass: book
github-repo: NOAA-EDAB/esp_data_aggregation

language:
  ui:
    chapter_name: "Section "

params: 
  species_ID: "Acadian redfish" # common name of species

  asmt_sum_source: "assessmentdata::stockAssessmentSummary"
  asmt_source: "assessmentdata::stockAssessmentData"
  survey_source: "survdat"
  
  ricky_survey_data: bio_survey # ricky survey data
  
  save: TRUE

  cache: FALSE
  
  path: "" # figure path
---

# `r params$species` {-}

```{r, setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.width = 8,
  fig.align = "center",
  fig.cap = params$species,
  fig.path = params$path
)
```

```{r, species_data}
species <- params$species_ID

# risk data
risk_data <- risk[risk$Species == species, ] %>%
  missing_na()

risk_year_hist_data <- risk_year_hist[risk_year_hist$Species == species, ] %>%
  missing_na()

risk_year_value_data <- risk_year_value[risk_year_value$Species == species, ] %>%
  missing_na()

risk_species_data <- risk_species[risk_species$Species == species, ] %>%
  missing_na()

# data
latlong_data <- latlong[latlong$Species == species, ]

survey_data <- survey[survey$Species == species, ]
cond_data <- cond[cond$Species == species, ]
diet_data <- allfh[allfh$Species == species, ]

asmt_data <- asmt[asmt$Species == species, ]
asmt_sum_data <- asmt_sum[asmt_sum$Species == species, ]
swept_data <- swept[swept$Species == species, ]

rec_data <- rec_catch[rec_catch$Species == species, ]
com_data <- com_catch[com_catch$Species == species, ]

# habitat vulnerability
hab_data <- ecodata::habitat_vulnerability %>%
  dplyr::filter(Species == species) %>%
  dplyr::select(-Species)
hab_data <- hab_data[, c(8, 1:7)]

# climate vulnerability
climate_data <- climate_vulnerability %>%
  dplyr::mutate(Species = Species %>%
    stringr::str_to_sentence()) %>%
  dplyr::filter(Species == species) %>%
  dplyr::select(-Species)
```

```{r, save_data, eval = params$save}

dir.create("data")

save_data(latlong_data, name = "latlong_data")

```

```{r, eval = FALSE}

save_data(survey_data, name = "survey_data")

save_data(cond_data, name = "cond_data")

save_data(diet_data, name = "diet_data")

save_data(asmt_data, name = "asmt_data")

save_data(asmt_sum_data, name = "asmt_sum_data")

save_data(swept_data, name = "swept_data")

save_data(rec_data, name = "rec_data")

save_data(com_data, name = "com_data")

save_data(hab_data, name = "hab_data")

save_data(climate_data, name = "climate_data")

save_data(risk_data, name = "risk_data")

save_data(risk_year_hist_data, name = "risk_year_hist_data")

save_data(risk_year_value_data, name = "risk_year_value_data")

save_data(risk_species_data, name = "risk_species_data")
```

This is a preliminary report of previously collected data. This report is pulling information on all Northeast `r species` stocks.
