on:
  workflow_dispatch:

name: Deploy pkgdown

jobs: 
  build1:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Pandoc
        run: brew install pandoc
        shell: bash

      - name: Install command line packages
        run: |        
          sudo apt update
          sudo apt-get install  libgdal-dev libcurl4-gnutls-dev libgit2-dev libudunits2-dev
        shell: bash
        
      - name: Set up R
        uses: r-lib/actions/setup-r@master
        with: 
          r-version: '4.0.3' # problem with using 4.0.4        
      
      - name: Cache R packages
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.R_LIBS_USER }}
          key: big-cache-DESCRIPTION-02172021-2

      - name: Load R packages (if not cached)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo R CMD javareconf
          Rscript -e 'install.packages(c("pkgdown", "stringi", "car"))
          
      - name: Render pkgdown
        run: |
          Rscript -e 'pkgdown::build_site()'
          
      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          token: ${{ secrets.GH_PAT }}
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          target-folder: docs
          clean: false # Automatically remove deleted files from the deploy branch
