on:
  push:
    branches: main

name: little_cache

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
 #     RENV_PATHS_ROOT: ~/.local/share/renv
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master

  #    - name: Install pandoc
  #      run: |
  #        brew install pandoc
          
      - name: Cache packages
        uses: actions/cache@v1
        id: cache5
        with:
#          path: ${{ env.RENV_PATHS_ROOT }}
          key: cache5-renv-${{ hashFiles('renv.lock') }}
#          restore-keys: r-

      - name: Install renv and restore packages
        run: |
          R -e 'install.packages("renv")
          renv::restore()'
     
      - name: Install dependencies (if not cached)
        if: steps.cache5.outputs.cache-hit != 'true'
        run: |
          R -e 'install.packages(c("glue"))
          renv::snapshot()'
        
      - name: Deploy to github
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          TARGET_FOLDER: .
          CLEAN: true # Automatically remove deleted files from the deploy branch
