  
on:
  schedule:
    - cron: "0 0 * * 1,4"

name: Maintain bigger cache

jobs: 
  build:
    runs-on: ubuntu-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    
    steps:
      
      - name: Check cached R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: pkgdown-cache-05172021-AT
