  
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1,4"

name: Maintain bigger cache

jobs: 
  build:
    runs-on: ubuntu-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    
    steps:

      - name: Setup R
        uses: r-lib/actions/setup-r@master
        
      - name: Check cached R packages
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.R_LIBS_USER }}
          key: pkgdown-cache-05172021-AT
          
      - name: Load R packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo R CMD javareconf
          Rscript -e 'install.packages(c("stringi", "car", "devtools", "textshaping", "ragg", "pkgdown"), dependencies = TRUE)
          devtools::install_github("NOAA-EDAB/NEesp", ref = "v0.1.0", upgrade = "never")'
