on:
  push:
    branches: main

name: bookdown_reports

jobs: 
  build1:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    
    steps:
      - name: try action
        uses: NOAA-EDAB/esp_data_aggregation/bookdown/render@v1.3-beta
        with: 
          species: '1'
