on:
  push:
    branches: main

name: rmarkdown_test

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      RENV_PATHS_ROOT: ~/.local/share/renv
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Install pandoc
        run: |
          brew install pandoc
          
      - name: Cache packages
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: cache11-renv-${{ hashFiles('**/renv.lock') }}
     
      - name: Install renv and restore packages (if cache exists)
        if: steps.cache.outputs.cache-hit != 'false'
        run: |
          R -e 'install.packages("renv")
          renv::restore(lockfile = "~/.local/share/renv")'
          
      - name: Install dependencies (if not cached)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          R -e 'install.packages(c("rmarkdown"))'

      - name: Build site
        run: Rscript -e 'rmarkdown::render("test/index.Rmd", quiet = TRUE)'
        
      - name: Store lockfile (if not cached)
        if: steps.cache.outputs.cache-hit != 'true'
        run: R -e 'renv::snapshot(lockfile = "~/.local/share/renv")'

#      - name: Deploy to github
#        uses: JamesIves/github-pages-deploy-action@3.7.1
#        with:
#          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
#          BRANCH: gh-pages # The branch the action should deploy to.
#          FOLDER: . # The folder the action should deploy.
#          TARGET_FOLDER: .
#          CLEAN: true # Automatically remove deleted files from the deploy branch
